name = "mutual_eval_axioms"
version = "0.1.0"
defaultTargets = ["MutualEvaluation"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.0"


[[lean_lib]]
name = "MutualEvaluation"
globs = ["MutualEvaluation", "MutualEvaluation.Internal"]
leanOptions = {warningAsError = true}
